package com.spcollege.titanbank.bll;
// Generated Nov 22, 2013 10:42:19 PM by Hibernate Tools 3.2.1.GA



/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private int addressId;
     private String city;
     private String state;
     private String zip;
     private String streetAddress;

    public int getAddressId() {
        return addressId;
    }

    public void setAddressId(int addressId) {
        this.addressId = addressId;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getStreetAddress() {
        return streetAddress;
    }

    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress;
    }

    



}


